name: AWS to OIDC connectivity

on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Choose Terraform Action
        options:
          - apply
          - destroy
permissions:
  id-token: write
  contents: read   


jobs:
  job1:
    runs-on: ubuntu-slim

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6.1.0
        
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::570290071608:role/github-role
          
        

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload tfplan to registry
        uses: actions/upload-artifact@v7.0.1
        with:
          name: terraform-plan
          path: tfplan

  job2:
    runs-on: ubuntu-slim
    environment: production
    needs: job1
    

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6.1.0

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::570290071608:role/github-role

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: Terraform Download
        uses: uses: actions/download-artifact@v7.0.0
        with:
          name: terraform-plan
          path: .

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Apply
        run: terraform ${{ inputs.action }} --auto-approve tfplan
        
          
        
    
